services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: kc_event_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      SAB_BACKEND_BASE_URL: "http://host.docker.internal:8081"
    volumes:
      - ./providers:/opt/keycloak/providers
    ports:
      - "8085:8080"
    command:
      - start-dev
    networks:
      - keycloak_network

# Persistent volumes configuration
volumes:
  postgres_data:
  pgadmin:
# Network configuration
networks:
  keycloak_network:
    driver: bridge